# Algebra Linear

## Matrizes

In [2]:
matriz_A = [[1,2,3],[4,5,6]]
print(matriz_A)

[[1, 2, 3], [4, 5, 6]]


In [3]:
#Primeira linha
print(matriz_A[0])

[1, 2, 3]


In [5]:
# elemento da primeira linha e primeira coluna
print(matriz_A[0][0])

1


### Usando NumPy

In [8]:
import numpy as np

matriz_B = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(matriz_B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Matriz transposta

In [10]:
matriz_transposta_B = matriz_B.transpose() # matriz_B.T
matriz_transposta_B

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### Adição de matriz

In [11]:
matriz_transposta_B + matriz_B

array([[ 2,  6, 10],
       [ 6, 10, 14],
       [10, 14, 18]])

### Multiplicação de Matriz

In [13]:
matriz_A = np.array([[1,2],[3,4],[5,6]])
matriz_B = np.array([[7],[8]])

np.dot(matriz_A,matriz_B)

array([[23],
       [53],
       [83]])

## Matrizes Espaciais

### Matriz Inversa

o produto vetoriral da Matriz com a sua Inversa resulta na matriz identidade

A matriz tem que ser quadrada e determinantes diferente de zero

In [16]:
matriz_A = np.array([[1,1,-3],[2,1,3],[2,0,-1]])

In [17]:
# DETERMINANTE
np.linalg.det(matriz_A)

13.0

In [21]:
# CALCULANDO A INVERSA
inversa_A = np.linalg.inv(matriz_A)
print(inversa_A)

[[-0.07692308  0.07692308  0.46153846]
 [ 0.61538462  0.38461538 -0.69230769]
 [-0.15384615  0.15384615 -0.07692308]]


In [23]:

np.dot(matriz_A,inversa_A) # matriz identidade: diagonal principal igual a 1 e resto igual a zero

array([[ 1.00000000e+00, -5.55111512e-17,  5.55111512e-17],
       [ 0.00000000e+00,  1.00000000e+00,  5.55111512e-17],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

### Matriz identidade

In [24]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Transformações Lineares

In [26]:
import numpy as np

In [27]:
# vetor original
v = np.array([[1],[1]])
print(v)

[[1]
 [1]]


### Rotação

In [28]:
# rotação
theta = np.pi/4.0

# matriz de rotação
R = np.array([[np.cos(theta), -np.sin(theta)],[np.cos(theta), np.sin(theta)]])

# vetor rotacionado
rotated_v = np.dot(R, v)
print(rotated_v)

[[0.        ]
 [1.41421356]]


### Escalonamento

In [30]:
S = np.array([[2,0],[0,0.5]])
scaled_v = np.dot(S, v)
print(scaled_v)

[[2. ]
 [0.5]]


### Reflexão


In [31]:
F = np.array([[1,0],[0,-1]])
reflected_v = np.dot(F,v)
print(reflected_v)

[[ 1]
 [-1]]


### Cisalhamento

In [32]:
H = np.array([[1,0.5],[0,1]])
sheared_v = np.dot(H, v)
print(sheared_v)

[[1.5]
 [1. ]]


## Autovalores e Autovetores

In [33]:
# definindo a matriz A
A = np.array([[6,-1],[2,3]])

In [36]:
# calculando os autovalores e autovetores
autovalores, autovetores = np.linalg.eig(A)

print('Autovalores:')
print(autovalores)
print('\n')
print('Autovetores (normalizados):')
print(autovetores)

Autovalores:
[5. 4.]


Autovetores (normalizados):
[[0.70710678 0.4472136 ]
 [0.70710678 0.89442719]]


## Produto Escalar

In [41]:
v = np.array([4,6])
w = np.array([3,5])

In [42]:
np.dot(v,w)

42